### ISSUE TITLE
test report based sharding

### ISSUE THREAD

**Issue by shrynx** [reibitto/sbt-test-shards#4]
I tried out this library and our CI went from 32 mins to 16 mins using 6 shards which is great but some of the shards were not balanced as their are based on suits
i wonder if i use test report based one does , how does it handle newly added tests.
To be clear i will be using test report generated from last successful test run and say in a new MR i would be adding new tests that were not part of the previous test reports. will these new tests be distributed evenly too ?

**Comment by reibitto** [comment]
Yeah, you should get much better reductions in time than that if you can get it to balance properly. I describe what needs to be done in this section in the README (towards the bottom):
https://github.com/reibitto/sbt-test-shards?tab=readme-ov-file#sharding-algorithms

But to answer your question, for the very first test run everything is a "new test" so it's just distributed randomly. But after that the JUnit xml test reports will be in the `target` folders. You need to take these xml reports and store them somewhere so you can retrieve them later. Such as S3, some kind of remote cache, Maven/Nexus repo, or even commiting it in git (not really recommended but it's an option). Once you do that, you can pull the reports down in CI and then point `ShardingAlgorithm.Balance.fromJUnitReports(...)` to whatever folder you download them into.

In the future I'd like to make this part more automatic somehow. Like creating an additional sbt task that can upload the test reports somewhere. Then in CI you simply call that sbt task after everything is green. The tricky part of writing such a task within `sbt-test-shards` is that there isn't one solution... if I upload to S3, then that's not going to work for some people who don't use AWS, etc. Which means I'd likely need to write multiple extensions to handle the various remote stores people might use.

Until then, unfortunately the uploading/downloading of test reports is something that needs to be handled in the project consuming this plugin.

If that's too much work for you right now, maybe you can identify the most expensive tests and manually shard only those? Just an idea. It would be imperfect, but will get you better results than pure random.

**Comment by shrynx** [comment]
Oh i totally understand that. i am going to use the last run's report upload on S3
but the new run might have additional test which were not present in the last successful run. so my question is are they ignored or distributed between the shards ?

**Comment by reibitto** [comment]
The new test suites will run too. By default, if a corresponding test report is not found it'll randomly distribute by suite name. But you can specify the fallback algorithm with whatever you want (even something entirely custom) by passing in `fallbackShardingAlgorithm` to the `fromJUnitReports` method.

**Comment by shrynx** [comment]
Ahh perfect !
thanks. will try it out then
